services:
  app:
    command: bun run dev
    build: .
    develop:
      watch:
        - action: sync
          path: ./
          target: /app
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json
    environment:
      - PATH=/usr/local/bin/bun:$PATH
      - NODE_ENV=development
    ports:
      - 5173:5173
    volumes:
      - ./src:/app/src:ro
      - ./package.json:/app/package.json
